name: CI/CD Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ap-southeast-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan.out | tee tfplan.log
        timeout-minutes: 10

      - name: Upload Terraform Plan Log
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-log
          path: terraform/tfplan.log

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        timeout-minutes: 10

      - name: Terraform Output
        working-directory: terraform
        run: terraform output
